### ISSUE TITLE
pwned password check not working

### ISSUE THREAD

**Issue by scifire91** [ltb-project/self-service-password#228]
after update to 1.3 i tried to enable the pwned password check but i can´t change passwords anymore causer there is a php fatal error:

`PHP Fatal error:  Uncaught Error: Call to undefined function PwnedPasswords\\curl_init() in /usr/share/self-service-password/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php:94\nStack trace:\n#0 /usr/share/self-service-password/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(62): PwnedPasswords\\PwnedPasswords->fetchCurl('https://api.pwn...')\n#1 /usr/share/self-service-password/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(134): PwnedPasswords\\PwnedPasswords->fetch('https://api.pwn...')\n#2 /usr/share/self-service-password/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(152): PwnedPasswords\\PwnedPasswords->getCount(NULL)\n#3 /usr/share/self-service-password/lib/functions.inc.php(267): PwnedPasswords\\PwnedPasswords->isInsecure('1qay"WSX3edc')\n#4 /usr/share/self-service-password/pages/change.php(169): check_password_strength('1qay"WSX3edc', 'wmz#CDi!NF4PZH@...', Array, 'test.user@proem...')\n#5 /usr/share/self-service-passwo in /usr/share/self-service-password/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php on line 94, referer: https://password.mywebsite.com/index.php`

On the site the user won´t see any error it´s just an empty page with the logo.

Anyway thanks for this nice feature!

**Comment by scifire91** [comment]
@plewin Thanks, that was missing. curl was already installed but not php-curl.
Maybe a hint in the patch-notes would also be helpful.
