### ISSUE TITLE
use_pwnedpasswords = true

### ISSUE THREAD

**Issue by sentiblue** [ltb-project/self-service-password#434]
Hey guys...

I've been able to customize the project to run on windows and it has been working perfectly.
I'm trying to enable pwnedpasswords, I set
$use_pwnedpasswords = true;

I read the code on
lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php

I made sure there's network permissions for the server to reach API at api.pwnedpasswords.com on port 443

But when I test an account reset, it doesn't change the pw, nor tell me whether the pw has been pawned. I deliberately use "Password_123!" to make sure it triggers the notification but I only get a page with full header, logo, etc... but no messages.

Am I missing something else?

**Comment by coudot** [comment]
Did you tried to set debug mode?

**Comment by sentiblue** [comment]
I should mention that in php.ini, I have enabled the following line, which is needed for the feature.

extension=php_curl.dll

Thx coudot for labeling the question.

**Comment by sentiblue** [comment]
Coudot: I enabled debug and found this error

[27-Oct-2020 10:26:33 America/Los_Angeles] PHP Warning:  file_get_contents(): Failed to enable crypto in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php on line 83

Does that mean I have the wrong crypto option enabled?

**Comment by coudot** [comment]
No idea, maybe PHP on windows is not compatible with crypto

**Comment by sentiblue** [comment]
Looks like change.php is getting passed a null value because pwnpassword.php cannot make a connection due to cert related issue. My full debug is below, but I'm quite unsure how to resolve the certificate part. Thoughts?

<quote>
[27-Oct-2020 10:42:04 America/Los_Angeles] PHP Notice:  Undefined variable: obscure_failure_messages in C:\inetpub\ssp\pages\change.php on line 186
[27-Oct-2020 10:42:04 America/Los_Angeles] PHP Warning:  in_array() expects parameter 2 to be array, null given in C:\inetpub\ssp\pages\change.php on line 186
[27-Oct-2020 10:42:04 America/Los_Angeles] PHP Notice:  Undefined variable: display_posthook_error in C:\inetpub\ssp\pages\change.php on line 193
[27-Oct-2020 10:42:19 America/Los_Angeles] PHP Notice:  Undefined variable: obscure_failure_messages in C:\inetpub\ssp\pages\change.php on line 186
[27-Oct-2020 10:42:19 America/Los_Angeles] PHP Warning:  in_array() expects parameter 2 to be array, null given in C:\inetpub\ssp\pages\change.php on line 186
[27-Oct-2020 10:42:19 America/Los_Angeles] PHP Notice:  Undefined variable: display_posthook_error in C:\inetpub\ssp\pages\change.php on line 193
[27-Oct-2020 10:42:26 America/Los_Angeles] PHP Warning:  file_get_contents(): SSL operation failed with code 1. OpenSSL Error messages:
error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php on line 83
[27-Oct-2020 10:42:26 America/Los_Angeles] PHP Warning:  file_get_contents(): Failed to enable crypto in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php on line 83
[27-Oct-2020 10:42:26 America/Los_Angeles] PHP Warning:  file_get_contents(https://api.pwnedpasswords.com/range/CD38E): failed to open stream: operation failed in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php on line 83
[27-Oct-2020 10:42:26 America/Los_Angeles] PHP Fatal error:  Uncaught RuntimeException: Failed to open stream. in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php:86
Stack trace:
#0 C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php(64): PwnedPasswords\PwnedPasswords->fetchFile('https://api.pwn...')
#1 C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php(134): PwnedPasswords\PwnedPasswords->fetch('https://api.pwn...')
#2 C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php(152): PwnedPasswords\PwnedPasswords->getCount(NULL)
#3 C:\inetpub\ssp\lib\functions.inc.php(267): PwnedPasswords\PwnedPasswords->isInsecure('<new_password>')
#4 C:\inetpub\ssp\pages\change.php(169): check_password_strength('<new_password>', '<old_password>', Array, 'testuser')
#5 C:\inetpub\ssp\index.php(224): include('C:\\inetpub\\ssp\\...')
#6 {main}
  thrown in C:\inetpub\ssp\lib\vendor\ron-maxweb\pwned-passwords\src\PwnedPasswords\PwnedPasswords.php on line 86
</quote>

**Comment by faust64** [comment]
Hi,

Checking code, it sounds like PHP wasn't able to connect PwnedPasswords API:

https://github.com/ltb-project/self-service-password/blob/v1.3/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php#L83-L86

Is there any firewall filtering outbound connections? Some HTTP proxy that should be used maybe?

**Comment by faust64** [comment]
The `SSL operation failed with code 1. OpenSSL Error messages: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed` suggests PHP could not connect the PwnedPasswords API, failing to verify its certificate.
Any chance there would be some proxy intercepting connections leaving your LAN, generating certificates signed by some custom authority?

There should be a way to feed PHP with the proper authorities.
Not being familiar with Windows, I guess you could try something like this: https://mlocati.github.io/articles/official-and-custom-certification-authorities.html
