### ISSUE TITLE
Debug not working & PwnedPasswords issue

### ISSUE THREAD

**Issue by Kipjr** [ltb-project/self-service-password#492]
Version: 1.3
PHP 7.3
After a regular update of our webserver we've encountered this: 
```
[Sat Apr 03 17:13:47.305343 2021] [php7:error] [pid 23765] [client 83.86.182.14:59528] PHP Fatal error:  Uncaught Error: Call to undefined function PwnedPasswords\\curl_init() in DIRECTORY/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php:94
Stack trace:
#0 DIRECTORY/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(62): PwnedPasswords\\PwnedPasswords->fetchCurl('https://api.pwn...')
#1 DIRECTORY/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(134): PwnedPasswords\\PwnedPasswords->fetch('https://api.pwn...')
#2 DIRECTORY/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php(152): PwnedPasswords\\PwnedPasswords->getCount(NULL)
#3 DIRECTORY/lib/functions.inc.php(267): PwnedPasswords\\PwnedPasswords->isInsecure('ThisisSecureOrNot?@')
#4 DIRECTORY/pages/resetbytoken.php(181): check_password_strength('ThisisSecureOrNot?@', '', Array, 'mysusername')
#5 DIRECTORY/index.php(224): include('DIRECTORY...')
#6 {main}
  thrown in DIRECTORY/lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php on line 94, referer: https://MYWEBPAGE/index.php?action=resetbytoken&token=3vUCAHcsFoVoWLGhMvzUohjvOZ8=

[Sat Apr 03 17:13:32.061578 2021] [php7:notice] [pid 21889] [client 83.86.182.14:56196] PHP Notice:  Undefined variable: source in DIRECTORY/pages/resetbytoken.php on line 220, referer: https://MYWEBPAGE/index.php?action=resetbytoken&token=3vUCAHcsFoVoWLGhMVd3BR
```

I managed to fix this by disabling the PwnedPasswords feature. 

However, even though I had debugging enabled this was not shown at all. Only in /var/log/apache2/ssp_error.log I found this issue.

**Comment by faust64** [comment]
the `Call to undefined function PwnedPasswords\\curl_init()` message, as well as line 94 from `lib/vendor/ron-maxweb/pwned-passwords/src/PwnedPasswords/PwnedPasswords.php`, both suggest there was an issue loading PHP curl library.

Any chance that module used to load, and no longer does since upgrading?
