### ISSUE TITLE
Compatibility with PHP 8.1

### ISSUE THREAD

**Issue by coudot** [ltb-project/self-service-password#662]
PHP LDAP has changed between 8.0 and 8.1, some adaptations in the code may be needed.

Example:
```
#1 /usr/share/self-service-password/htdocs/index.php(179): require_once('...')
#2 {main}
  thrown in /usr/share/self-service-password/lib/functions.inc.php on line 301
[17-Jun-2022 09:07:34 Europe/Paris] PHP Fatal error:  Uncaught Error: Cannot use object of type LDAP\ResultEntry as array in /usr/share/self-service-password/lib/functions.inc.php:301
Stack trace:

**Comment by artlog** [comment]
working on

**Comment by artlog** [comment]
Did not manage to reproduce problem as documented in first comment.
Tested on ubuntu 22.04 with PHP 8.1.2 (cli) (built: Jul 21 2022 12:10:37) (NTS)

Still some other problems can occur since in php 8.1 some php warn have been upgraded to fatal errors with exceptions.

One found when using questions to change password and question were not created in ldap. with an older php it just logs errors 

```
[Thu Aug 18 13:38:41.958699 2022] [php7:warn] [pid 28] [client 172.18.0.1:41610] PHP Warning:  hash_equals(): Expected known_string to be a string, null given in /var/www/html/resetbyquestions.php on line 201, referer: http://0.0.0.0:6080/?action=resetbyquestions
```

with php 8.1 it fails with 
```
[Thu Aug 18 14:39:57.002143 2022] [php:error] [pid 2557] [client 172.17.0.1:52320] PHP Fatal error:  Uncaught TypeError: hash_equals(): Argument #1 ($known_string) must be of type string, null given in /usr/share/self-service-password/htdocs/resetbyquestions.php:201\nStack trace:\n#0 /usr/share/self-service-password/htdocs/resetbyquestions.php(201): hash_equals()\n#1 /usr/share/self-service-password/htdocs/index.php(183): require_once('...')\n#2 {main}\n  thrown in /usr/share/self-service-password/htdocs/resetbyquestions.php on line 201, referer: http://ssp.jammy.dev.worteks.com/?action=resetbyquestions
```
will fill a bug for it.

**Comment by artlog** [comment]
php 8.1 related : https://github.com/ltb-project/self-service-password/issues/697

This is not a blocking issue since it does not prevent to change password when it should.

**Comment by coudot** [comment]
All seems now work with PHP 8

**Comment by coudot** [comment]
I found a new issue:
```
==> /var/log/apache2/other_vhosts_access.log <==
ssp.example.com:80 127.0.0.1 - - [01/Sep/2022:17:46:45 +0200] "POST / HTTP/1.1" 500 185 "http://ssp.example.com/" "Mozilla/5.0 (X11; Linux x86_64; rv:104.0) Gecko/20100101 Firefox/104.0"

==> /var/log/apache2/error.log <==
[Thu Sep 01 17:46:47.554271 2022] [php:error] [pid 155018] [client 127.0.0.1:39632] PHP Fatal error:  Uncaught Error: Non-static method LtbAttributeValue::ldap_get_mail_for_notification() cannot be called statically in /usr/local/ssp/rest/v1/adminchangepassword.php:73\nStack trace:\n#0 {main}\n  thrown in /usr/local/ssp/rest/v1/adminchangepassword.php on line 73

**Comment by coudot** [comment]
Hope all is working now with PHP 8.1 :crossed_fingers:

**Comment by coudot** [comment]
Try @artlog suggestion: https://github.com/ltb-project/self-service-password/commit/ffa90966726812744bed0bb59010a6d379dba8de#commitcomment-82817671
