### ISSUE TITLE
Problem to install on EL9

### ISSUE THREAD

**Issue by Gokusan31** [ltb-project/self-service-password#760]
Hello,

I'm trying to install self service password on el9 with rpm package self-service-password-1.5.2-1.el9.noarch.rpm but got a smarty dependancy error:

```
Loaded plugins: builddep, changelog, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, groups-manager, kpatch, needs-restarting, playground, product-id, repoclosure, repodiff, repograph, repomanage, reposync, subscription-manager, uploadprofile
Updating Subscription Management repositories.
DNF version: 4.10.0
Command: dnf install /root/self-service-password-1.5.2-1.el9.noarch.rpm 
Installroot: /
Releasever: 9
cachedir: /var/cache/dnf
Base command: install
Extra commands: ['install', '/root/self-service-password-1.5.2-1.el9.noarch.rpm']
User-Agent: constructed: 'libdnf (AlmaLinux 9.0; generic; Linux.x86_64)'
elrepo-9-x64                                                                                                                                 423 kB/s | 2.0 kB     00:00    
reviving: 'Elrepo_elrepo-9-x64' can be revived - repomd matches.
Elrepo_elrepo-9-x64: using metadata from Tue 14 Feb 2023 05:00:35 AM CET.
rpmfusion-el9-x64                                                                                                                            550 kB/s | 2.3 kB     00:00    
reviving: 'RPMFusion_rpmfusion-el9-x64' can be revived - repomd matches.
RPMFusion_rpmfusion-el9-x64: using metadata from Fri 10 Feb 2023 02:48:33 PM CET.
epel-9-x64                                                                                                                                   407 kB/s | 2.3 kB     00:00    
reviving: 'EPEL_epel-9-x64' can be revived - repomd matches.
EPEL_epel-9-x64: using metadata from Thu 16 Feb 2023 03:50:37 PM CET.
almalinux-stream-9-x64                                                                                                                       580 kB/s | 2.6 kB     00:00    
reviving: 'AlmaLinux_almalinux-stream-9-x64' can be revived - repomd matches.
AlmaLinux_almalinux-stream-9-x64: using metadata from Thu 16 Feb 2023 05:04:51 AM CET.
almalinux-extras-9-x64                                                                                                                       563 kB/s | 2.3 kB     00:00    
reviving: 'AlmaLinux_almalinux-extras-9-x64' can be revived - repomd matches.
AlmaLinux_almalinux-extras-9-x64: using metadata from Fri 10 Feb 2023 02:40:52 PM CET.
almalinux-base-9-x64                                                                                                                         447 kB/s | 2.3 kB     00:00    
reviving: 'AlmaLinux_almalinux-base-9-x64' can be revived - repomd matches.
AlmaLinux_almalinux-base-9-x64: using metadata from Wed 15 Feb 2023 05:05:32 AM CET.
timer: sack setup: 502 ms
--> Starting dependency resolution
--> Finished dependency resolution
timer: depsolve: 215 ms

Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 130, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.9/site-packages/dnf/cli/main.py", line 166, in resolving
    base.resolve(cli.demands.allow_erasing)
  File "/usr/lib/python3.9/site-packages/dnf/base.py", line 878, in resolve
    raise exc
dnf.exceptions.DepsolveError: 
 Problem: conflicting requests
  - nothing provides php-Smarty needed by self-service-password-1.5.2-1.el9.noarch
Error: 
 Problem: conflicting requests
  - nothing provides php-Smarty needed by self-service-password-1.5.2-1.el9.noarch
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
Cleaning up.
```

I download latest smarty 4.3 as zip, unzip into /usr/share/php/smarty3 (tried to rename as smarty4 to) and copy everything from libs folder to parent folder as mentioned on smarty website.

Still getting the error message when i try to install self service rpm. Any idea ?

Thanks

**Comment by coudot** [comment]
It seems indeed that php-Smarty is no more available on EL8 and EL9, we need to drop the dependency requirements (we can keep it for EL7).

For now, you can try to force RPM installation with:
```
rpm --nodeps -ivh https://ltb-project.org/archives/self-service-password-1.5.2-1.el9.noarch.rpm

**Comment by Gokusan31** [comment]
Hello,

Okay rpm installed with --nodeps, but index.php is not loading cause of php-smarty i think.

php-smarty was unzip to /usr/share/php/

**Comment by coudot** [comment]
You need to configure the SMARTY configuration parameter to fit the path of your Smarty installation.

**Comment by Gokusan31** [comment]
Thank, smarty path was update to my smarty installation path.

Now, got a blank page with this in httpd logs:

```
[Tue Mar 14 14:29:38.976112 2023] [authz_core:debug] [pid 290653:tid 290764] mod_authz_core.c(815): [client X.X.X.X:50608] AH01626: authorization result of <RequireAny>: granted
[Tue Mar 14 14:29:38.976140 2023] [proxy:debug] [pid 290653:tid 290764] mod_proxy.c(1512): [client X.X.X.X:50608] AH01143: Running scheme unix handler (attempt 0)
[Tue Mar 14 14:29:38.976152 2023] [proxy_ajp:debug] [pid 290653:tid 290764] mod_proxy_ajp.c(764): [client X.X.X.X:50608] AH00894: declining URL fcgi://localhost/usr/share/self-service-password/htdocs/index.php
[Tue Mar 14 14:29:38.976163 2023] [proxy_fcgi:debug] [pid 290653:tid 290764] mod_proxy_fcgi.c(1054): [client 11.172.1.42:50608] AH01076: url: fcgi://localhost/usr/share/self-service-password/htdocs/index.php proxyname: (null) proxyport: 0
[Tue Mar 14 14:29:38.976172 2023] [proxy_fcgi:debug] [pid 290653:tid 290764] mod_proxy_fcgi.c(1063): [client 11.172.1.42:50608] AH01078: serving URL fcgi://localhost/usr/share/self-service-password/htdocs/index.php
[Tue Mar 14 14:29:38.976182 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(2532): AH00942: FCGI: has acquired connection for (*)
[Tue Mar 14 14:29:38.976192 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(2588): [client X.X.X.X:50608] AH00944: connecting fcgi://localhost/usr/share/self-service-password/htdocs/index.php to localhost:8000
[Tue Mar 14 14:29:38.976202 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(2624): [client X.X.X.X:50608] AH02545: fcgi: has determined UDS as /run/php-fpm/www.sock
[Tue Mar 14 14:29:38.976304 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(2814): [client X.X.X.X:50608] AH00947: connected /usr/share/self-service-password/htdocs/index.php to httpd-UDS:0
[Tue Mar 14 14:29:38.976444 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(3182): AH02823: FCGI: connection established with Unix domain socket /run/php-fpm/www.sock (*)
[Tue Mar 14 14:29:38.977251 2023] [proxy:debug] [pid 290653:tid 290764] proxy_util.c(2547): AH00943: FCGI: has released connection for (*)
[Tue Mar 14 14:29:38.977497 2023] [ssl:debug] [pid 290653:tid 290764] ssl_engine_io.c(1151): [client X.X.X.X:50608] AH02001: Connection closed to child 2 with standard shutdown (server X.X.X.X:443)
```

Saw a localhost:8000 in log, don't what is it but netstat output nothing on that port.

**Comment by coudot** [comment]
localhost:8000 is not something linked to Self Service Password but with you web server configuration.

**Comment by Gokusan31** [comment]
yes, something not important because i got this kind of log for a long time on an other website without issue to access it.

Will try to search why self service password page won't display and informe you when i found the root cause

**Comment by markus-96** [comment]
I am using AlmaLinux 8, but with the yum-repository mentioned here: https://self-service-password.readthedocs.io/en/latest/installation.html#centos-redhat
In this repository for EL8, https://ltb-project.org/rpm/8/noarch/,  there is php-Smarty provided, but not for EL9: https://ltb-project.org/rpm/9/noarch/. I do not know why this is, I do not see anything that should prevent providing php-Smarty, maybe even the exact same package, for EL9.

**Comment by coudot** [comment]
I think the solution will be to add Smarty as composer dependency (see #728), and remove it only for distributions that ship the package.

**Comment by Gokusan31** [comment]
> I am using AlmaLinux 8, but with the yum-repository mentioned here: https://self-service-password.readthedocs.io/en/latest/installation.html#centos-redhat In this repository for EL8, https://ltb-project.org/rpm/8/noarch/, there is php-Smarty provided, but not for EL9: https://ltb-project.org/rpm/9/noarch/. I do not know why this is, I do not see anything that should prevent providing php-Smarty, maybe even the exact same package, for EL9.

Awesome Man !! Works like a charm with the el8 rpm. Thank you very much!

**Comment by coudot** [comment]
In Service Desk, I choosed to remove the dependency on php-Smarty, the package should now be installed manually. We will do this for the moment.

**Comment by paulignari** [comment]
In debian stable smarty3 package is present and working, the missing dependence breaks the installation.

It is possible to restore the smarty3 dependence in the deb package config packaging/debian/control?

**Comment by markus-96** [comment]
I think it would be great if this could also be covered in the documentation for RHEL(-derivates), like it is done for Debian/Ubuntu. The problem is that there is no one actively maintaining php-Smarty for RHEL 8 and 9. The one rpm available for RHEL 8 is by remi, that was not updated since 2018.

Something like:

- Download Smarty and unzip to /usr/local/share/php/Smarty
- add `define("SMARTY", "/usr/local/share/php/Smarty/Smarty.class.php");` to your `config.inc.local.php`

These are two easy steps, but if not mentioned make it really painful to install on RHEL.
