### ISSUE TITLE
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array

### ISSUE THREAD

**Issue by ermont49** [ltb-project/self-service-password#798]
Hello,
SSP on debian 12, openldap 2.5.13, php 8.2.7, nginx 1.22.1

ISSUE: after complete form (username, oldpasswd,newpasswd,newpasswd) click on Send, then " This page isn’t working"

LOGS: 
```
2023/08/23 15:45:21 [error] 386431#386431: *6 FastCGI sent in stderr: "PHP message: PHP Warning:  preg_match_all(): Unknown modifier '=' in /usr/share/self-service-password/lib/functions.inc.php on line 253; PHP message: PHP Warning:  Trying to access array offset on value of type null in /usr/share/self-service-password/lib/functions.inc.php on line 254; PHP message: PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, null given in /usr/share/self-service-password/lib/functions.inc.php:254
Stack trace:
#0 /usr/share/self-service-password/htdocs/change.php(184): check_password_strength()
#1 /usr/share/self-service-password/htdocs/index.php(174): require_once('...')
#2 {main}
  thrown in /usr/share/self-service-password/lib/functions.inc.php on line 254" while reading response header from upstream, client: localhost, server: localhost, request: "POST / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php8.2-fpm.sock:", host: "localhost", referrer: "http://localhost/"
```
One idea ? Thanks

**Comment by coudot** [comment]
Hello @ermont49 

seems linked to your configuration of `$pwd_forbidden_chars`. If you have `/` in it, then the search will fail because of the regexp delimiters (see https://stackoverflow.com/questions/20705399/warning-preg-replace-unknown-modifier). A solution is to escape `/` or to remove if from the configuration if not needed.

**Comment by ermont49** [comment]
Hello Coudot
its works !
I remove "/" in config.inc.php at $pwd_forbidden_chars
great thanks :)
